Update graph.py
python2/3 fix: hexlify is not able to take strings as arguments

>>> hexlify('123')
TypeError: a bytes-like object is required, not 'str'

this will fix that and it is a nicer solution imho (maybe we can skip the round. I think it doesn't matter)